### PR TITLE
Update file_helper.py

### PR DESCRIPTION
**Pull request by monkeysm8**
Removed GoBuster.
Swapped HTML2TEXT for W3M as it gives a cleaner output.
Removed direct paths to user and password files.

### CODE REVIEW

**Comment by codingo** [comment]
Hey, were you intending on forking this back to the main project? I've reviewed your changes and I'm more than happy to merge it into master if you can raise the pr correctly.

**Review by codingo — APPROVED** [review]
Please feel free to raise a pr to merge these into the main project (github.com/codingo/Reconnoitre) - I'd love to have them included.

**Comment by monkeysm8** [comment]
Done dude :)

**Comment by codingo** [comment]
Awesome. Now merged back to master :)

**Pull request merged**
